import "./globals.css";

import type { Metadata } from "next";
import PeriodicTable from "./PeriodicTable";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(): React.ReactNode {
  return (
    <html lang="en">
      <body>
        <PeriodicTable />
      </body>
    </html>
  );
}